// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipvntlfcakeqjviziyen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwdm50bGZjYWtlcWp2aXppeWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDAyNTMsImV4cCI6MjA2Nzg3NjI1M30.dH0lWqFhH9XLkBGzN_I5R_i1UkVdUQb4F4mMGeOaElg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});